# Generated by Django 5.1.2 on 2025-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(db_table='user_role', related_name='role', to='sms.role'),
        ),
    ]
