# Generated by Django 5.1.2 on 2025-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_customuser_middle_name_alter_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='user_profile',
        ),
    ]
