# Generated by Django 5.1.2 on 2025-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_rename_role_customuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
