# Generated by Django 5.1.2 on 2025-06-24 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_country_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('habitation', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.IntegerField(blank=True, null=True)),
                ('zone_no', models.IntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('area_code', models.IntegerField(blank=True, null=True)),
                ('address_line', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'Address',
            },
        ),
    ]
