# Generated by Django 5.1.2 on 2025-06-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_department_options_alter_department_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Class Room Type',
                'verbose_name_plural': 'Class Room Types',
                'db_table': 'ClassRoomType',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.classroomtype')),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'db_table': 'ClassRoom',
            },
        ),
    ]
