# Generated by Django 5.1.2 on 2025-06-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_yearlevel_bankingdetails'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.classroom')),
                ('end_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_time', to='sms.period')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_time', to='sms.period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.term')),
            ],
            options={
                'verbose_name': 'ClassPeriod',
                'verbose_name_plural': 'ClassPeriods',
                'db_table': 'ClassPeriod',
            },
        ),
    ]
