# Generated by Django 5.1.2 on 2025-06-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_rename_user_profile_customuser_role'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('previous_school_name', models.CharField(max_length=200)),
                ('previous_standard_studied', models.CharField(max_length=200)),
                ('tc_letter', models.CharField(max_length=200)),
                ('emergency_contact_n0', models.CharField(max_length=100)),
                ('entire_road_distance_from_home_to_school', models.CharField(max_length=100)),
                ('obtain_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('previous_percentage', models.FloatField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.yearlevel')),
            ],
            options={
                'db_table': 'Admission',
            },
        ),
    ]
