# Generated by Django 5.1.2 on 2025-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='emergency_contact_n0',
            new_name='emergency_contact_no',
        ),
    ]
