# Generated by Django 5.1.2 on 2025-06-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_rename_emergency_contact_n0_admission_emergency_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addressuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
